version: '3.7'

services:
  mariadb-master:
    image: docker.io/bitnami/mariadb:10.7
    restart: always
    volumes:
      - 'mariadb_master_data:/bitnami/mariadb'
    environment:
      - BITNAMI_DEBUG=true
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=${MARIADB_REPLICATION_PASSWORD}
      - MARIADB_DATABASE=roykesyshop
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

  mariadb-slave:
    image: docker.io/bitnami/mariadb:10.7
    restart: always
    depends_on:
      - mariadb-master
    environment:
      - BITNAMI_DEBUG=true
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=${MARIADB_REPLICATION_PASSWORD}
      - MARIADB_DATABASE=roykesyshop
      - MARIADB_MASTER_HOST=mariadb-master
      - MARIADB_MASTER_PORT_NUMBER=3306
      - MARIADB_MASTER_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
     
  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mariadb-master
    restart: always
    depends_on:
      - mariadb-master
    ports:
      - 3310:8080

  backend:
    build: ./backend
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - mariadb-slave

  frontend:
    build:
      context: ./frontend
    restart: always
    volumes:
      - ./frontend/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx_conf:/etc/nginx/
    depends_on:
      - backend
      - frontend
    ports:
      - 80:80

volumes:
  mariadb_master_data:
    driver: local