db:
    master_host : mariadb-master
    slave_host : [mariadb-slave]
    user : input_user_name
    password : input_user_password
    database : input_database_name
    
jwt_secret_key: input_jwt_secret_key