version: '3.1'

services:
  db:
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    image: mariadb:10.3
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: roykesyshop
    ports:
      - 3306:3306
    networks:
      backend-network:
        ipv4_address: 10.5.0.2
  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: db
    restart: always
    depends_on:
      - db
    networks:
      backend-network:
        ipv4_address: 10.5.0.3
    ports:
      - 3310:8080


networks:
  backend-network:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1